# Generated by Django 4.1.2 on 2022-11-05 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ihas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihas',
            name='iha_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Ürün Fotoğrafı Seç'),
        ),
        migrations.AlterField(
            model_name='ihas',
            name='brand',
            field=models.CharField(max_length=40, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='ihas',
            name='category',
            field=models.CharField(max_length=20, verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='ihas',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulan Tarih'),
        ),
        migrations.AlterField(
            model_name='ihas',
            name='money',
            field=models.CharField(max_length=20, verbose_name='Fiyat'),
        ),
        migrations.AlterField(
            model_name='ihas',
            name='renter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kiralayan'),
        ),
        migrations.AlterField(
            model_name='ihas',
            name='weight',
            field=models.CharField(max_length=6, verbose_name='Ağırlık'),
        ),
    ]
